### PR TITLE
added function "semver_id_fwrite()"

### PR DESCRIPTION
**Pull request by marcomaggi**
This function is useful for debugging purposes.

### CODE REVIEW

**Comment by uael** [comment]
This implementation isn't cross platform and does not follow the global code style of the library.

**Comment by marcomaggi** [comment]
I do not understand why the build fails on AppVeyor: it looks like standard C99 to me, with variable length arrays.

About the code style: is it because of blanks, or variable naming, or both?

**Comment by uael** [comment]
The microsoft c compiler does not fully support c99 in old versions, I'm known this reduce the way to write code and force us to use bad patterns but I want the code to be Win compatible without using mingw or related.
No variables naming is fine, I just mean code formatting, I use this 
```c
void func_name(void) {
  /* do something */
}
```

**Comment by waruqi** [comment]
@uael Or we can use the `/TP` compile option on old msvc to compile C99 code as c++. Or add `set_languages("c99")` in `xmake.lua`. xmake will automatically handle C99 compilation problems on msvc.

**Comment by uael** [comment]
@waruqi cool :+1: 
Edit: @waruqi `set_languages("c99")` is already present in all targets

**Pull request closed without merging**
